# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'to_do_list' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for to_do_list

  target 'to_do_listTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'to_do_listUITests' do
    # Pods for testing
  end

  pod 'RealmSwift'
  pod 'Charts' 
  pod 'TinyConstraints'
  pod 'DropDown'
  pod 'CalendarKit'

end
